spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: route_pup_user
        uri: lb://pup-user
        order: 8000
        predicates: 
        - Path=/user/**
        filters:
        - StripPrefix=1
